version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6335
      - QDRANT__LOG_LEVEL=INFO

volumes:
  qdrant_data:
  
configs:
  qdrant_config:
    content: |
      log_level: INFO 

